### ISSUE TITLE
Who is maintaining what branch of Magister v2?

### ISSUE THREAD

**Issue by gruijter** [idiidk/magister-api#2]
Hi @idiidk 

Great to see you have added the new authentication scheme, and that you have published it as an npm package! I am however confused where the magister v2 is being maintained now. See also this issue:
https://github.com/simplyGits/MagisterJS/issues/76

Note: the 'original' v2 has recently gotten some commits by @lieuwex. Could you please align with him on where/how to maintain this package?

I do like to see all commits being published as npm package!

**Comment by lieuwex** [comment]
FWIW I've just released the first alpha version of magister.js v2

You can install it by using `npm install --save magister.js@2.0.0-alpha.0`, it isn't really tested 
 in a long time by me whatsoever.

This package isn't affiliated with Magister.js (it's completely newly written), but it may be a better alternative since it's actually maintained. I don't really know if @idiidk would rather continue on his own library or take over Magister.js. But that's up to him of course :)

**Comment by idiidk** [comment]
Just to clarify, I totally would like to continue with magister.js and just deprecate this package. To get to the point where MagisterJS already is would take a pretty long time so it would just be wasted effort.

**Comment by Sj3rd** [comment]
Ikr. I think that the best option too.

Weet je of magister.js ook een optie heeft om de auth data op te slaan zodat je later kan reautenticaten?

**Comment by gruijter** [comment]
Ok, that is super! I will try to keep using magister.js v2 then :)

Great that you are willing to maintain it by the way 👍

**Comment by idiidk** [comment]
@Sj3rd Save the bearer token from the Magister object and reauthenticate with that token. If it's expired the login will just fail I guess.

**Comment by Sj3rd** [comment]
@idiidk but how can I reauthenticate with the bearer token

I got the bearertoken by calling the login function

**Comment by idiidk** [comment]
@Sj3rd Set the parameter token on login {token: "IDIIDK"}

**Comment by Sj3rd** [comment]
But how do I call the login() function when there's no one logged in?

**Comment by idiidk** [comment]
@Sj3rd 

```Javascript
getSchools('<schoolname>') // get schools matching '<schoolname>'
	.then((schools) => schools[0]) // get the first school
	.then((school) => magister({ // login
		school,
		token: "THis?"
	}))
	.then((m) => { // done logging in, say hi
		console.log(`Hey ${m.profileInfo.firstName}!`);
	}, (err) => { // something went wrong
		console.error('something went wrong:', err);
	});
```

**Comment by Sj3rd** [comment]
```TypeError: Cannot read property 'replace' of undefined```

**Comment by Sj3rd** [comment]
mmmmm....... Dan krijg ik alleen een object terug met een bearer token en de schoolinformatie. profileInfo is null

**Comment by gruijter** [comment]
@idiidk @Sj3rd what is the benefit of re-authenticating with a token versus just logging in again with username/password?
I am pulling data from magister once an hour. What would be good practice to do then, concerning authentication.

**Comment by idiidk** [comment]
@gruijter Storing a token is a lot safer than just storing a plain password, but in your situation you probably still need to do that because tokens expire. We probably need to add token refreshing to MagisterJS to fully get rid of password storing.
