### ISSUE TITLE
Kan je m fixen?

### ISSUE THREAD

**Issue by PringlePot** [idiidk/magister-api#9]

**Comment by idiidk** [comment]
Ik heb geen magister account meer, sorry! Als ik jouw inlog zou mogen gebruiken kan ik het proberen ;D

**Comment by idiidk** [comment]
of gebruik deze: https://github.com/simplyGits/MagisterJS

**Comment by PringlePot** [comment]
Ok, ik ben nu zelf eentje aan t maken met de magister-scraper en deze

**Comment by PringlePot** [comment]
klaar: https://github.com/PringlePot/Magister-API
